# Generated by Django 5.0.3 on 2024-03-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avg_caffeine_intake_profile_duration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='duration_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='duration_type',
        ),
    ]
